server:
  port: 8080
spring:
  profiles:
    active: native
    # Active profile native buna ait conf dosyası varsa onuda çalıştırır.
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/emreokumus/spring_cloud_config_server #yapılandırmayı aramak için git konumunu bağlayacaktır. Uzak git repoyu kullanıyoruz.
          uri: https://github.com/emreokumus/${CONFIG_GIT_REPO_NAME}.git
          username: ${CONFIG_GIT_USERNAME}
          password: ${CONFIG_GIT_PASSWORD}
          cloneOnStart: true # Başlangıcında repoyu verify eder sorun olup olmadığına dair.
management:
  security:
    enabled: false
  # /env, /refresh vb. gibi yönetim noktalarında spring güvenliğini devre dışı bırakır.
  # Bu development ortamı için bir ayardır, production ortamında security aktif hale getirilmelidir.
